# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gitUrl',
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
