# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
