# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20170506_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspace.Theme', to_field='slug'),
        ),
    ]
