# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.Theme', to_field='slug'),
        ),
    ]
