# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170330_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='repoEmail',
        ),
    ]
