# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170330_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='repoAvatar',
            field=models.URLField(default=None, null=True),
        ),
    ]
